language: go

go:
  - "1.9"

before_install: go get github.com/mitchellh/gox
script:  make
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - build/junit-xml
    - build/junit-xml.exe
    - build/junit-xml_osx
  skip_cleanup: true
  on:
    tags: true